name: testing

#Cuango hagamos un pull en la rama main
on:
  pull_request:
  branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node
        uses: actions/setup_node@v1
        with:
        node-version: "16.17"
      - name: Installing Dependencies
        run: npm install

      - name: testing our app
      - run: npm test